name: Release

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

  #  - name: build
  #    uses: actions/checkout@v4
    - name: buils
      run: |
         echo "brrr" > executable
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v0.0.1"
        release_name: Release ${{ github.sha }}
        body: |
          Release ${{ github.sha }}
          
    - name: Upload release artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./executable
        asset_name: executable-${{ github.sha }}.exe
        asset_content_type: application/octet-stream
