
name: Clone repository Ubuntu

on: 
   workflow_dispatch:

jobs:
  clone_repo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python3 git git-lfs -y
        
        git clone https://github.com/dillongoostudios/goo-engine.git
        cd goo-engine
        ./build_files/build_environment/install_linux_packages.py


        sudo apt update
        sudo apt install build-essential git git-lfs subversion cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libegl-dev -y
        sudo apt install libwayland-dev wayland-protocols libxkbcommon-dev libdbus-1-dev linux-libc-dev -y

        ./build_files/utils/make_update.py --use-linux-libraries

        make update
        make

    - name: Find
      run: |
          ls
          cd goo-engine
          ls
          

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         tag_name: v4.0.0
         release_name: Release v4.0.0
         draft: false
         prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./goo-engine
         asset_name: goo-engine
         asset_content_type: application/octet-stream
   

