name: Build Blender

on: 
   workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Visual Studio
      uses: microsoft/setup-msbuild@v1.0.1
      with:
        vs-version: 'latest'
    
    - name: Install CMake
      run: |
        choco install cmake
      shell: cmd
      
    - name: Install Dependencies
      run: |
        choco install git -y
        git clone https://github.com/dillongoostudios/goo-engine.git
        cd ./goo-engine && dir
        git submodule update --init --recursive
        cd build_files
        call make.bat
      shell: cmd
    
    - name: Configure Blender
      run: |
        cmake -B build -G "Visual Studio 16 2019" -A x64
      shell: cmd
    
    - name: Build Blender
      run: |
        cmake --build build --config Release
      shell: cmd
